name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - week-4

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install semver
        run: npm install -g semver

      - name: Bump version
        run: |
          NEW_VERSION=$(semver bump patch $(git describe --tags --abbrev=0))
          git tag -a "$NEW_VERSION" -m "Automated tag"
          git push origin --tags

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        run: |
          docker build -t student-record-api:$NEW_VERSION .
          docker tag student-record-api:$NEW_VERSION ${{ secrets.DOCKER_USERNAME }}/student-record-api:$NEW_VERSION
          docker push ${{ secrets.DOCKER_USERNAME }}/student-record-api:$NEW_VERSION