name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - week-4

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        run: |
          docker build -t student-record-api:latest .
          docker tag student-record-api:latest ${{ secrets.DOCKER_USERNAME }}/student-record-api:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/student-record-api:latest
