name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - week-4

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Install semver
        run: npm install -g semver

      - name: Bump version
        run: |
          TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          NEW_VERSION=$(semver bump patch $TAG)

          # Ensure the new version is greater than the previous tag
          if git rev-parse "refs/tags/$NEW_VERSION" >/dev/null 2>&1; then
            echo "Tag $NEW_VERSION already exists. Incrementing..."
            NEW_VERSION=$(semver bump patch $(echo $NEW_VERSION))
          fi

          echo "New version: $NEW_VERSION"
          git tag -a "$NEW_VERSION" -m "Automated tag"
          git push origin --tags

      - name: Debug NEW_VERSION
        run: echo "NEW_VERSION is $NEW_VERSION"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        run: |
          if [ -z "$NEW_VERSION" ]; then
            echo "Error: NEW_VERSION is empty. Exiting."
            exit 1
          fi
          docker build -t student-record-api:$NEW_VERSION .
          docker tag student-record-api:$NEW_VERSION ${{ secrets.DOCKER_USERNAME }}/student-record-api:$NEW_VERSION
          docker push ${{ secrets.DOCKER_USERNAME }}/student-record-api:$NEW_VERSION
